sudo: required
services:
  - docker

before_install:
  - docker build -t talhamustafa/react-docker -f Dockerfile.dev .


script:
  - docker run -e CI=true talhamustafa/react-docker npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-962298719074"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY